# version: '3.8'

networks:
  inception:
    name: inception42
    driver: bridge

services:
  mariadb:
    image: mariadb
    build: ./requirements/mariadb/
    networks:
      - inception
    restart: always
    volumes:
      # - /home/llacsivy/data/mariadb:/var/lib/mysql
      - /Users/llacsivy/Coding-Projects/Inception/data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=wp_db
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=123
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=123

    #   - .env
    ports:
      - "3306:3306"
    secrets:
      - db_root_password
      - db_password
    # healthcheck:
    #   test:
    #     interval: 20s
    #     timeout: 10s
    #     retries: 10
    #     start_period: 10s

  dev:
    image: dev_helper
    build: ./requirements/dev/
    depends_on:
      - mariadb
    networks:
      - inception
    stdin_open: true
    tty: true

  # wordpress:
  #   image: wordpress:latest
  #   build: ./requirements/wordpress
  #   depends_on:
  #     - mariadb
  #   restart: always
  #   volumes:
  #     - /home/llacsivy/data/wordpress:/var/www/html
  #   ports:
  #     - "80:80"
  #   environment:
  #     WORDPRESS_DB_USER: wp_user
  #     WORDPRESS_DB_PASSWORD: wp_db_password
  #     WORDPRESS_DB_HOST: db:3306

  nginx:
    image: nginx
    build: ./requirements/nginx
    # volumes:
    #   - /Users/llacsivy/Coding-Projects/Inception/data/wordpress:/var/www/html
    ports:
      - 443:443
    # depends_on:
    #   wordpress:
    #     condition: service_healthy
    # environment:
    #   DOMAIN_NAME=${DOMAIN_NAME}

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_password:
    file: ../secrets/wp_password.txt




# volumes:
#   mariadb_data:
#     name: mariadb_vol
#     driver: local
#     driver-opts:
#       type: none
#       o: bind
#       device: /home/llacsivy/data/mariadb
#   wordpress_data:
#     name: wordpress_vol
#     driver: local
#     driver-opts:
#       type: none
#       o: bind
#       device: /home/llacsivy/data/wordpress