networks:
  inception:
    name: inception42
    driver: bridge

services:
  mariadb:
    image: mariadb
    build: ./requirements/mariadb/
    restart: always
    volumes:
      - type: bind
        source: /home/llacsivy/data/mariadb
        target: /var/lib/mysql
    environment:
      - MYSQL_DATABASE=wp_db
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=123
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=123

    networks:
      - inception
    ports:
      - "3306:3306"
    secrets:
      - db_root_password
      - db_password

  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: always
    volumes:
      - type: bind
        source: /home/llacsivy/data/wordpress
        target: /var/www/html
    networks:
      - inception
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: wordpress

  nginx:
    image: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    volumes:
      - type: bind
        source: /home/llacsivy/data/wordpress
        target: /var/www/html
    networks:
      - inception
    ports:
      - 443:443

  dev:
    image: dev_helper
    build: ./requirements/dev/
    depends_on:
      - mariadb
    networks:
      - inception
    stdin_open: true
    tty: true

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_password:
    file: ../secrets/wp_password.txt




# volumes:
#   mariadb_data:
#     name: mariadb_vol
#     driver: local
#     driver-opts:
#       type: none
#       o: bind
#       device: /home/llacsivy/data/mariadb
#   wordpress_data:
#     name: wordpress_vol
#     driver: local
#     driver-opts:
#       type: none
#       o: bind
#       device: /home/llacsivy/data/wordpress