version: '3.8'

networks:
  inception:
    name: inception42
    driver: bridge

services:
  db:
    image: maria:latest
    # build:
    #   context: ./requirements/mariadb/
    #   dockerfile: ./requirements/mariadb/Dockerfile
    networks:
      - inception
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    # healthcheck:
    #   test:
    #     interval: 20s
    #     timeout: 10s
    #     retries: 10
    #     start_period: 10s

  dev:
    image: dev_helper
    # build:
    #   context: ./requirements/dev/
    #   dockerfile: ./requirements/dev/Dockerfile
    networks:
      - inception
    stdin_open: true
    tty: true


  # wordpress:
  #   image: wordpress:latest
  #   depends_on:
  #     - db
  #   restart: always
  #   volumes:
  #     - wp_data:/var/www/html
  #   ports:
  #     - "80:80"
  #   environment:
  #     WORDPRESS_DB_USER: wp_user
  #     WORDPRESS_DB_PASSWORD: wp_db_password
      # WORDPRESS_DB_HOST: db:3306

  # nginx:
  #   build: ./requirements/nginx
  #   volumes: wp_data:/var/www/html
  #   ports:
  #     - 443:443
  #   depends_on:
  #     wordpress:
  #       condition: service_healthy
  #   environment:
  #     DOMAIN_NAME=${DOMAIN_NAME}


volumes:
  db_data:
  # wp_data:


secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_password:
    file: ../secrets/wp_password.txt